-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJHXsn3ytQMJxVobw
+gHdn32AbDGUDaSnoVvt8NAy0LKgCgYIKoZIzj0DAQehRANCAATZu7JVmID4BhkE
fFEm6mXZmGvbiLDBLBITvUic/IZUigxLHfpfYf92oUvEolC0Paqy8a/Yy3Cso+Sn
GmVAHqXS
-----END PRIVATE KEY-----